#!/usr/bin/env tsx
/**
 * Discover and ingest videos from the source channel.
 *
 *   npm run ingest                    # newest 50, Data API if YOUTUBE_API_KEY is set
 *   npm run ingest -- --limit 200     # the whole channel (136 videos today)
 *   npm run ingest -- --refresh       # also refresh metadata on videos already stored
 *   npm run ingest -- --sql           # print SQL instead of writing (no service key needed)
 *   npm run ingest -- --source=fallback
 *
 * Source selection: the Data API is used whenever `YOUTUBE_API_KEY` is present, because it
 * is documented, stable and costs about 6 quota units for the entire channel. Without a
 * key the degraded HTML path is used and every run is logged as `ingest_degraded`, so a
 * run that relied on scraping is never mistaken for a normal one.
 *
 * The fallback is deliberately slow. A listing page gives only relative dates ("2 weeks
 * ago"), which is not good enough for a publishing calendar, so the exact publish instant
 * comes from one watch-page request per video, spaced out. That is fine for a handful of
 * videos and wrong for hundreds — which is why the API path exists.
 */
import process from 'node:process';
import { createApiSource } from '../src/lib/youtube/api';
import { createFallbackSource } from '../src/lib/youtube/fallback';
import { normaliseVideo } from '../src/lib/youtube/eligibility';
import type { VideoSource } from '../src/lib/youtube/types';

const CHANNEL_ID = process.env.YOUTUBE_CHANNEL_ID ?? 'UC79E6KatRfXbmdWVWGncsew';
const CHANNEL_HANDLE = '@BacsiTranVanPhucOfficial';

function flag(name: string): string | undefined {
  const match = process.argv.find((arg) => arg === `--${name}` || arg.startsWith(`--${name}=`));
  if (match === undefined) return undefined;
  return match.includes('=') ? match.split('=')[1] : '';
}

const limit = Number.parseInt(flag('limit') ?? '50', 10);
const sqlMode = flag('sql') !== undefined;
const refresh = flag('refresh') !== undefined;
const forcedSource = flag('source');
const apiKey = process.env.YOUTUBE_API_KEY;

function chooseSource(): VideoSource {
  const useApi =
    forcedSource === 'api' || (forcedSource === undefined && apiKey !== undefined && apiKey !== '');

  if (useApi) {
    if (apiKey === undefined || apiKey === '') {
      throw new Error('--source=api needs YOUTUBE_API_KEY to be set');
    }
    console.error(`source: YouTube Data API v3 (channel ${CHANNEL_ID})`);
    return createApiSource({ apiKey, channelId: CHANNEL_ID });
  }

  console.error(
    'source: HTML fallback (DEGRADED — set YOUTUBE_API_KEY for the documented API path).\n' +
      '        One watch-page request per video, spaced 1.2s apart.',
  );
  return createFallbackSource({ channelHandle: CHANNEL_HANDLE, requestDelayMs: 1200 });
}

function lit(value: string | number | boolean | null): string {
  if (value === null) return 'null';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${value.replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const source = chooseSource();

  if (!sqlMode) {
    // Writing needs the service role, which only exists server-side.
    const { ingestChannel } = await import('../src/lib/youtube/ingest');
    const outcome = await ingestChannel({ source, limit, refreshExisting: refresh });
    console.log(JSON.stringify(outcome, null, 2));
    if (outcome.errors.length > 0) process.exitCode = 1;
    return;
  }

  // SQL mode: do the discovery and normalisation, emit an idempotent upsert, write nothing.
  const discovered = await source.listUploads(limit);
  console.error(`discovered ${discovered.length} videos; fetching details…`);

  const details = await source.fetchDetails(discovered.map((video) => video.youtubeVideoId));
  console.error(`fetched ${details.length} of ${discovered.length}`);

  const rows = details.map((video) => normaliseVideo(video));

  const values = rows
    .map(
      (row) => `  (${lit(row.youtubeVideoId)}, ${lit(row.title)},
   ${lit(row.episodeNumber ?? null)}, ${lit(row.descriptionRaw)}, ${lit(row.descriptionClean)},
   ${lit(row.lowSignal)}, ${lit(JSON.stringify(row.keywords))}::jsonb,
   ${lit(JSON.stringify(row.chapters))}::jsonb,
   ${lit(row.durationSeconds ?? null)}, ${lit(row.viewCount ?? null)},
   ${lit(JSON.stringify(row.thumbnails))}::jsonb, ${lit(row.publishedAt)}::timestamptz,
   ${lit(row.eligible ? 'available' : 'ineligible')}, ${lit(row.ineligibleReason ?? null)})`,
    )
    .join(',\n');

  process.stdout.write(`-- Generated by scripts/backfill-youtube.ts (--sql). ${rows.length} videos.
-- Idempotent: an existing row has only its mutable metadata refreshed. status is never
-- touched, so a 'used' video can never be resurrected by re-running this.
insert into internal.youtube_videos (
  youtube_video_id, title, episode_number, description_raw, description_clean,
  low_signal, keywords, chapters, duration_seconds, view_count,
  thumbnails, published_at, status, ineligible_reason
)
select v.youtube_video_id, v.title, v.episode_number, v.description_raw, v.description_clean,
       v.low_signal, array(select jsonb_array_elements_text(v.keywords)), v.chapters,
       v.duration_seconds, v.view_count, v.thumbnails, v.published_at,
       v.status::internal.video_status, v.ineligible_reason
from (values
${values}
) as v(youtube_video_id, title, episode_number, description_raw, description_clean,
       low_signal, keywords, chapters, duration_seconds, view_count,
       thumbnails, published_at, status, ineligible_reason)
on conflict (youtube_video_id) do update set
  title = excluded.title,
  episode_number = excluded.episode_number,
  description_raw = excluded.description_raw,
  description_clean = excluded.description_clean,
  low_signal = excluded.low_signal,
  keywords = excluded.keywords,
  chapters = excluded.chapters,
  duration_seconds = excluded.duration_seconds,
  view_count = excluded.view_count,
  thumbnails = excluded.thumbnails;
`);
}

await main();
